# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_APIKEY" >> ~/.pypirc
      - run:
          name: make packages
          command: |
            python setup.py sdist && python3 setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            if [ $(git log -1 --format=format:%H --full-diff dioptra/__init__.py) = $(git rev-parse HEAD) ]; then pip install twine && twine upload dist/*; else echo "no go"; fi

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context:
            - pypi-creds
          filters:
            branches:
              only:
                - main

